version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    restart: always