name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhubusername/fastapi-app .
          docker push yourdockerhubusername/fastapi-app

      - name: Deploy to server
        run: |
          ssh user@server 'docker pull yourdockerhubusername/fastapi-app && docker-compose up -d'